### ISSUE TITLE
Error while Training shapenet

### ISSUE THREAD

**Issue by lookquad** [mutianxu/GDANet#2]
Please have a look at following error- 

Traceback (most recent call last):
  File "main_ptseg.py", line 440, in <module>
    train(args, io)
  File "main_ptseg.py", line 91, in train
    print("The number of training data is:%d", len(train_data))
  File "/home/phiai/anaconda3/envs/gdanet/lib/python3.5/site-packages/torch/utils/data/dataset.py", line 20, in __len__
    raise NotImplementedError
NotImplementedError

**Comment by mutianxu** [comment]
Hi @lookquad ,

Did you correctly download the dataset and symlink the path following our README?

**Comment by lookquad** [comment]
Yes, Data and path is all good. Actually there is no __len__ function in your data_util file PartNormalDataset  class. That is why it was throwing this error. I figured it out and corrected. Will send a pull request once done.
Thank You for your reply.

**Comment by mutianxu** [comment]
Hi @lookquad ,

Thanks for point out this! We have corrected this.
