### ISSUE TITLE
pred = pred.max(dim=2)[1]，IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

### ISSUE THREAD

**Issue by sapphire666** [mutianxu/GDANet#5]
In utils.py ,line 51:
def compute_overall_iou(pred, target, num_classes):
    shape_ious = []
    pred= pred.max(dim=1)[1].data  # the correct dimension
    # pred = pred.max(dim=2)[1]    # (batch_size, num_points)  the pred_class_idx of each point in each sample

**Comment by mutianxu** [comment]
The bug has been fixed.
